redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "D:\\NEW THING\\aud.io\\build\\web"
publishOrigin = "config"
commandOrigin = "config"
command = "if [ ! -d _flutter ]; then git clone https://github.com/flutter/flutter.git -b 3.44.0 --depth 1 _flutter; fi && _flutter/bin/flutter build web --release --dart-define=BASE_URL=https://aud-io-1.onrender.com"
base = "D:\\NEW THING\\aud.io"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]