FROM debian:bookworm-slim AS build

# Install Flutter
RUN apt-get update && apt-get install -y curl git unzip xz-utils libglu1-mesa && \
    rm -rf /var/lib/apt/lists/*

RUN curl -s https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.19.6-stable.tar.xz | tar xJ -C /opt && \
    ln -s /opt/flutter/bin/flutter /usr/local/bin/flutter && \
    ln -s /opt/flutter/bin/dart /usr/local/bin/dart

ENV PATH="/opt/flutter/bin:$PATH"

RUN flutter doctor -v

WORKDIR /app
COPY pubspec.yaml pubspec.lock ./
RUN flutter pub get
COPY . .
RUN flutter build web --dart-define=BASE_URL=https://aud-io-1.onrender.com

FROM nginx:alpine
COPY --from=build /app/build/web /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]