services:
  - type: web
    name: aud-io-server
    runtime: docker
    repo: https://github.com/0giinn0/Aud.io
    branch: main
    dockerfilePath: Dockerfile
    dockerContext: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: PODCAST_INDEX_API_KEY
        sync: false
      - key: PODCAST_INDEX_API_SECRET
        sync: false
      - key: PODCAST_INDEX_USER_AGENT
        value: aud.io/1.0
      - key: SOUNDCLOUD_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_ID
        value: c2a22ea075c24aefb1f0d35506c3cecd
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: SPOTIFY_REDIRECT_URI
        value: https://aud-io-web.pages.dev/callback